[package]
name = "solana-geyser-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tonic = "0.14"
futures = "0.3"
log = "0.4"
env_logger = "0.11"
bs58 = "0.5"
anyhow = "1.0"

yellowstone-grpc-proto = "10.1.1"
yellowstone-grpc-client = "10.2.0"